// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: proto/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_AgentConnect_FullMethodName         = "/liveagent.gateway.v1.AgentGateway/AgentConnect"
	AgentGateway_AgentTerminalConnect_FullMethodName = "/liveagent.gateway.v1.AgentGateway/AgentTerminalConnect"
	AgentGateway_Authenticate_FullMethodName         = "/liveagent.gateway.v1.AgentGateway/Authenticate"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayClient interface {
	AgentConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, GatewayEnvelope], error)
	AgentTerminalConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalStreamFrame, TerminalStreamFrame], error)
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) AgentConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, GatewayEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_AgentConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEnvelope, GatewayEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentConnectClient = grpc.BidiStreamingClient[AgentEnvelope, GatewayEnvelope]

func (c *agentGatewayClient) AgentTerminalConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalStreamFrame, TerminalStreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[1], AgentGateway_AgentTerminalConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalStreamFrame, TerminalStreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentTerminalConnectClient = grpc.BidiStreamingClient[TerminalStreamFrame, TerminalStreamFrame]

func (c *agentGatewayClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AgentGateway_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
type AgentGatewayServer interface {
	AgentConnect(grpc.BidiStreamingServer[AgentEnvelope, GatewayEnvelope]) error
	AgentTerminalConnect(grpc.BidiStreamingServer[TerminalStreamFrame, TerminalStreamFrame]) error
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) AgentConnect(grpc.BidiStreamingServer[AgentEnvelope, GatewayEnvelope]) error {
	return status.Error(codes.Unimplemented, "method AgentConnect not implemented")
}
func (UnimplementedAgentGatewayServer) AgentTerminalConnect(grpc.BidiStreamingServer[TerminalStreamFrame, TerminalStreamFrame]) error {
	return status.Error(codes.Unimplemented, "method AgentTerminalConnect not implemented")
}
func (UnimplementedAgentGatewayServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_AgentConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).AgentConnect(&grpc.GenericServerStream[AgentEnvelope, GatewayEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentConnectServer = grpc.BidiStreamingServer[AgentEnvelope, GatewayEnvelope]

func _AgentGateway_AgentTerminalConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).AgentTerminalConnect(&grpc.GenericServerStream[TerminalStreamFrame, TerminalStreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentTerminalConnectServer = grpc.BidiStreamingServer[TerminalStreamFrame, TerminalStreamFrame]

func _AgentGateway_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liveagent.gateway.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AgentGateway_Authenticate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentConnect",
			Handler:       _AgentGateway_AgentConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AgentTerminalConnect",
			Handler:       _AgentGateway_AgentTerminalConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/gateway.proto",
}
